version: '3.3'

services:
  moviedb:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: 'moviedb'
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'andy'
      MYSQL_ROOT_PASSWORD: 'andy'
    ports:
      - '3307:3306'
    expose:
      - '3306'
    volumes:
      - ./01-createtable.sql:/docker-entrypoint-initdb.d/01-createtable.sql
      - ./02-movie-data.sql:/docker-entrypoint-initdb.d/02-movie-data.sql
      - ./03-add-star.sql:/docker-entrypoint-initdb.d/03-add-star.sql
      - my-db:/var/lib/mysql
    command: ["--general-log=ON"]

volumes:
  my-db:
