version: '3.3'

services:
  moviedb:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: 'moviedb'
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'andy'
      MYSQL_ROOT_PASSWORD: 'andy'
    ports:
      - '3307:3306'
    expose:
      - '3306'
    volumes:
      - ./createtable.sql:/docker-entrypoint-initdb.d/createtable.sql
      - ./movie-data.sql:/docker-entrypoint-initdb.d/movie-data.sql
      - my-db:/var/lib/mysql
    command: ["--general-log=ON"] #enable logging
volumes:
  my-db:


